-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 20:31:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Publicaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Publicaciones` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `Publicaciones` ;

-- -----------------------------------------------------
-- Table `Publicaciones`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Publicaciones`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Publicaciones`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `genero` INT NULL,
  `fecha_nac` DATE NULL,
  `password` VARCHAR(45) NULL,
  `contacto` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Publicaciones`.`Publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Publicaciones`.`Publicaciones` ;

CREATE TABLE IF NOT EXISTS `Publicaciones`.`Publicaciones` (
  `idPublicaciones` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `descripcion` TEXT(500) NULL,
  `titulo_publicacion` MEDIUMTEXT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idPublicaciones`),
  INDEX `fk_Publicaciones_Usuarios_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Publicaciones_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Publicaciones`.`Usuarios` (`idUsuarios`),
    INDEX `fk_Publicaciones_Categorias_idx` (`Categorias_idCategorias` ASC) VISIBLE,
	CONSTRAINT `fk_Publicaciones_Categorias`
    FOREIGN KEY (`Categorias_idCategorias`)
    REFERENCES `Publicaciones`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Publicaciones`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Publicaciones`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `Publicaciones`.`Categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tipo` INT NULL,
  `id_principal` INT NOT NULL,
  `Publicaciones_idPublicaciones` INT NOT NULL,
  PRIMARY KEY (`idCategorias`),
  INDEX `fk_Categorias_Publicaciones1_idx` (`Publicaciones_idPublicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_Categorias_Publicaciones1`
    FOREIGN KEY (`Publicaciones_idPublicaciones`)
    REFERENCES `Publicaciones`.`Publicaciones` (`idPublicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Publicaciones`.`Comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Publicaciones`.`Comentarios` ;

CREATE TABLE IF NOT EXISTS `Publicaciones`.`Comentarios` (
  `idComentarios` INT NOT NULL AUTO_INCREMENT,
  `comentario` TEXT(500) NULL,
  `fecha` DATE NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Publicaciones_idPublicaciones` INT NOT NULL,
  PRIMARY KEY (`idComentarios`),
  INDEX `fk_Comentarios_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Comentarios_Publicaciones1_idx` (`Publicaciones_idPublicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_Comentarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Publicaciones`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Publicaciones1`
    FOREIGN KEY (`Publicaciones_idPublicaciones`)
    REFERENCES `Publicaciones`.`Publicaciones` (`idPublicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Insertar 15 usuarios
INSERT INTO `Publicaciones`.`Usuarios` (nombre, apellidos, correo_electronico, genero, fecha_nac, password, contacto) VALUES -- 1 = MASCULINO Y 2 = FEMENINO
('Jose', 'Orozco', 'JoseOrozco1@egmail.com', 1, '2001-01-01', 'password1', '12345678'),
('Juan', 'Navarro', 'JuanNavarro2@gmail.com', 1, '2002-12-02', 'password2', '12345891'),
('Marvin', 'Velasquez', 'MarvinVela3@gmail.com', 1, '2002-12-02', 'password15', '12567899'),
('Josue', 'Velasquez', 'JosueVel4@gmail.com', 1, '2002-12-02', 'password1', '98765432'),
('Manuel', 'Orozco', 'ManuelOro5@gmail.com', 1, '2002-12-02', 'password5', '23456789'),
('Eduardo', 'Monzon', 'MonzonEdu6@gmail.com', 1, '2002-12-02', 'password6', '12567899'),
('Fernando', 'Orozco', 'FernandoOrozco7@gmail.com', 1, '2002-12-02', 'password7', '21345467'),
('Rony', 'Navarro', 'RonyNavarro8@gmail.com', 1, '2002-12-02', 'password8', '12345891'),
('Eunice', 'Fuentes', 'EuniFuentes9@gmail.com', 2, '2002-12-02', 'password9', '12567899'),
('Jimmy', 'Garcia', 'JimmyGarcia10@gmail.com', 1, '2002-12-02', 'password10', '12345678'),
('Juan', 'Lopez', 'JuanLopez11@gmail.com', 1, '2002-12-02', 'password11', '12345891'),
('Joa', 'Velasquez', 'JoaVela12@gmail.com', 1, '2002-12-02', 'password12', '12567899'),
('Rabi', 'Navarro', 'RabiNavarro13@egmail.com', 1, '2002-12-02', 'password13', '12345678'),
('Silvio', 'Fernandez', 'SilvioFernandez14@gmail.com', 1, '2002-12-02', 'password14', '12345891'),
('Cesar', 'Salgado', 'CesarSalgado15@gmail.com', 1, '2002-12-02', 'password15', '12567899');

-- Insertar 30 publicaciones
INSERT INTO `Publicaciones`.`Publicaciones` (fecha, hora, descripcion, titulo_publicacion, Usuarios_idUsuarios) VALUES
('2002-12-02', '12:00:00', 'El fútbol es un deporte de equipo jugado entre dos conjuntos de 11 jugadores cada uno, que intentan llevar el balón hacia la portería del equipo contrario y marcar goles. Se juega en un campo rectangular con una portería en cada extremo. El objetivo principal es marcar más goles que el equipo rival para ganar el partido. Es el deporte más popular y practicado en el mundo, con millones de aficionados y jugadores en todos los rincones del planeta.', 'Futbol', 1),
('2002-12-02', '12:10:00', 'Lionel Messi es un futbolista argentino considerado uno de los mejores jugadores de fútbol de todos los tiempos. Nacido el 24 de junio de 1987 en Rosario, Argentina, Messi comenzó su carrera en las divisiones juveniles del FC Barcelona, donde rápidamente mostró un talento excepcional. Debutó con el primer equipo del Barcelona en 2004 y desde entonces ha tenido una carrera extraordinaria, ganando numerosos títulos tanto a nivel individual como colectivo.
Messi es conocido por su habilidad excepcional con el balón, su visión de juego, su precisión en los pases y su capacidad para marcar goles de todas las formas posibles. Ha ganado múltiples Balones de Oro, premios que reconocen al mejor jugador del mundo, y ha establecido numerosos récords, tanto en el Barcelona como en la selección argentina. En 2021, Messi dejó el Barcelona y se unió al Paris Saint-Germain (PSG), donde continúa demostrando su calidad y talento.', 'Messi', 2),
('2002-12-02', '12:20:00', 'La tecnología se refiere al conjunto de conocimientos técnicos, ordenados científicamente, que permiten diseñar y crear bienes y servicios que facilitan la adaptación al medio ambiente y satisfacen las necesidades de las personas. También se puede definir como el conjunto de instrumentos, medios y técnicas que se utilizan para lograr un objetivo concreto, especialmente en áreas como la industria, la ciencia, la comunicación y la informática.
La tecnología abarca desde herramientas simples, como un martillo o una rueda, hasta dispositivos más complejos, como los ordenadores y los teléfonos inteligentes. Ha tenido un impacto significativo en la sociedad, transformando la forma en que vivimos, trabajamos y nos relacionamos. La tecnología también ha impulsado el desarrollo económico y ha contribuido a la solución de muchos problemas sociales y ambientales.', 'Tecnologia', 3),
('2002-12-02', '12:30:00', 'La programación es el proceso de diseñar, codificar, depurar y mantener el código fuente de programas de computadora. Se utiliza para crear software, que son conjuntos de instrucciones que permiten a las computadoras realizar diversas tareas. Los programadores escriben código en lenguajes de programación como Python, Java, C++, entre otros, para crear aplicaciones, sitios web, juegos, sistemas operativos y mucho más.

La programación requiere habilidades lógicas y creativas para resolver problemas y diseñar soluciones eficientes. Los programadores también deben tener un buen entendimiento de cómo funcionan las computadoras y de los principios de la programación. La programación es una habilidad fundamental en la era digital y ofrece oportunidades profesionales en una amplia variedad de campos.', 'Programacion', 4),
('2002-12-02', '12:40:00', 'La música es un arte que se manifiesta a través de la combinación de sonidos y silencios organizados de acuerdo con ciertas pautas y principios. Es una forma de expresión cultural que ha estado presente en todas las sociedades humanas a lo largo de la historia. La música puede ser vocal, instrumental o una combinación de ambas, y se puede clasificar en diversos géneros y estilos, como el clásico, el jazz, el rock, la música electrónica, entre otros.

Además de ser una forma de expresión artística, la música tiene efectos emocionales, psicológicos y sociales en las personas. Puede transmitir emociones, contar historias, crear ambientes y promover la cohesión social. La música también desempeña un papel importante en diversas ceremonias y rituales culturales en todo el mundo.', 'Musica', 5),
('2002-12-02', '12:50:00', 'La naturaleza se refiere al mundo físico y material que nos rodea, incluyendo todos los seres vivos, los paisajes, los fenómenos naturales y los recursos naturales. Es el conjunto de elementos que no han sido creados por la intervención humana, en contraposición a lo artificial.

La naturaleza es una fuente de inspiración y belleza para muchas personas, y desempeña un papel fundamental en el equilibrio de los ecosistemas y en el mantenimiento de la vida en la Tierra. Sin embargo, también enfrenta diversos desafíos debido a la actividad humana, como la deforestación, la contaminación y el cambio climático, que amenazan la biodiversidad y la sostenibilidad de los ecosistemas naturales. Es importante cuidar y proteger la naturaleza para garantizar un futuro saludable para nuestro planeta y todas las formas de vida que lo habitan.', 'Naturaleza', 6),
('2002-12-02', '12:59:00', 'El baloncesto, también conocido como básquetbol o simplemente básquet, es un deporte de equipo que se juega entre dos conjuntos de cinco jugadores cada uno, con el objetivo de encestar la pelota en el aro contrario, que está a una altura de 3.05 metros sobre el suelo. El equipo que anota más puntos al final del tiempo reglamentario gana el partido.
El baloncesto se juega en una cancha rectangular con un aro en cada extremo. Los jugadores pueden moverse por la cancha driblando (botando) la pelota o pasándola entre compañeros de equipo. Se pueden realizar tiros de campo desde diversas distancias y también tiros libres después de cometerse una falta.
El baloncesto es uno de los deportes más populares en todo el mundo, con millones de aficionados y jugadores de todas las edades. Es conocido por su ritmo rápido, su intensidad y su espectacularidad, con jugadas impresionantes y emocionantes que lo hacen muy atractivo para los espectadores.', 'Baloncesto', 7),
('2002-12-02', '13:10:00', 'El fútbol americano es un deporte de equipo en el que dos equipos compiten por avanzar el balón hacia la zona de anotación del equipo contrario. Se juega en un campo rectangular con líneas de yardas marcadas y el objetivo es anotar puntos llevando el balón hasta la zona de anotación o mediante patadas entre los postes de la portería. Es especialmente popular en Estados Unidos.', 'Futbol Americano', 8),
('2002-12-02', '13:20:00', 'El golf es un deporte en el que los jugadores golpean una bola hacia un hoyo en el menor número de golpes posible. Se juega en campos con 18 hoyos y requiere precisión y habilidad.', 'Golf', 8),
('2002-12-02', '13:30:00', 'El ciclismo es un deporte en el que los ciclistas compiten en carreras o recorridos utilizando bicicletas. Puede ser en carretera, montaña, pista o BMX, entre otros tipos de ciclismo. Es un deporte que combina resistencia, velocidad y habilidad técnica, y es practicado tanto a nivel competitivo como recreativo en todo el mundo.', 'Ciclismo', 8),
('2002-12-02', '13:40:00', 'El turismo es la actividad de viajar a lugares fuera del entorno habitual por placer, ocio o negocios. Implica una serie de actividades como transporte, alojamiento, alimentación, recreación y visita a lugares de interés cultural, natural o histórico. El turismo contribuye significativamente a la economía de muchos países al generar empleo y promover el desarrollo local.', 'Turismo', 9),
('2002-12-02', '12:00:00', 'El fútbol sala, también conocido como futsal, es una variante del fútbol que se juega en una cancha más pequeña y con equipos de cinco jugadores cada uno. Se juega en un espacio cerrado o al aire libre, con un balón más pequeño y pesado que el de fútbol tradicional. El fútbol sala se caracteriza por ser un juego rápido y dinámico, que requiere habilidad técnica, rapidez y precisión en los movimientos. Es muy popular en muchos países, especialmente en América Latina y Europa, y se juegan torneos y competiciones a nivel nacional e internacional.', 'Futbol Sala', 1),
('2002-12-02', '12:10:00', 'El fútbol 7 es una variante del fútbol que se juega con siete jugadores por equipo en lugar de los once habituales. Se juega en una cancha de tamaño reducido, con reglas adaptadas para este formato. El fútbol 7 es popular en competiciones amateur y juveniles, ya que requiere menos jugadores y espacio que el fútbol tradicional, pero conserva la dinámica y emoción del juego. Es una opción atractiva para quienes desean practicar fútbol de manera más informal o en un ambiente menos competitivo.', 'Futbol 7', 2),
('2002-12-02', '12:20:00', 'El fútbol 8 es una variante del fútbol que se juega con ocho jugadores por equipo en una cancha de tamaño reducido. Es una opción intermedia entre el fútbol tradicional de 11 jugadores y el fútbol 7, que se juega con siete jugadores por equipo. El fútbol 8 suele ser popular en ligas infantiles y juveniles, ya que permite una mayor participación de jugadores en comparación con el fútbol 11, pero mantiene algunas características del juego tradicional.', 'Futbol 8', 3),
('2002-12-02', '12:30:00', 'El fútbol amateur se refiere a la práctica del fútbol que se realiza de forma no profesional, es decir, sin recibir remuneración por jugar. Los equipos de fútbol amateur suelen estar formados por jugadores aficionados que juegan por pasión al deporte y por diversión. El fútbol amateur se juega en ligas locales, torneos comunitarios o entre amigos, y es una parte importante de la cultura futbolística en muchas comunidades. Muchos jugadores profesionales de fútbol comenzaron sus carreras en el fútbol amateur antes de dar el salto al fútbol profesional.', 'Futbol Amateur', 4),
('2002-12-02', '12:40:00', '"Pop" es un término abreviado de "popular", y se utiliza para referirse a un género musical amplio que abarca diversos estilos musicales que tienen en común su popularidad entre el público general. La música pop suele tener melodías pegajosas, letras simples y pegadizas, y un enfoque en la producción y el aspecto comercial. A lo largo de las décadas, el pop ha evolucionado y ha incorporado influencias de diversos géneros musicales, como el rock, el hip-hop, la electrónica y el R&B, entre otros.', 'Pop', 5),
('2002-12-02', '12:50:00', 'La bachata es un género musical y un estilo de baile originario de la República Dominicana. Se caracteriza por sus ritmos sensuales y románticos, así como por sus letras melancólicas que suelen hablar de amor y desamor. La bachata se ha popularizado en todo el mundo y ha evolucionado a lo largo de los años, incorporando influencias de otros géneros musicales como el pop y la música urbana. Es un género muy popular en América Latina y en comunidades latinas en otros países.', 'Bachata', 6),
('2002-12-02', '12:59:00', 'El rock es un género musical que se originó en la década de 1950 en Estados Unidos y se ha convertido en uno de los estilos musicales más influyentes y populares en todo el mundo. Se caracteriza por el uso prominente de la guitarra eléctrica, el bajo y la batería, así como por su ritmo enérgico y sus letras a menudo centradas en temas sociales, políticos o emocionales.
El rock ha dado lugar a numerosos subgéneros a lo largo de los años, como el rock and roll, el rock clásico, el rock alternativo, el punk rock, el hard rock, el metal, entre otros. Ha sido una fuerza importante en la cultura popular y ha influido en otros géneros musicales, la moda, el arte y la sociedad en general.', 'Rock', 7),
('2002-12-02', '13:10:00', 'Los corridos son un género musical tradicional de México que cuenta historias o relatos narrativos sobre eventos históricos, hazañas de personajes populares, amoríos, tragedias o temas de actualidad. Se caracterizan por su ritmo rápido y enérgico, acompañado típicamente por instrumentos como la guitarra, el acordeón, el bajo sexto y la percusión.
Los corridos han evolucionado a lo largo del tiempo y han abordado una amplia gama de temas, desde relatos de la Revolución Mexicana hasta historias de narcotráfico y crimen organizado en la actualidad. Aunque tradicionalmente se transmitían de forma oral, hoy en día se pueden encontrar corridos grabados en diferentes estilos y formatos, manteniendo su popularidad en México y entre las comunidades hispanohablantes en Estados Unidos y otros países.', 'Corridos', 8),
('2002-12-02', '13:20:00', 'El alpinismo, también conocido como montañismo, es una actividad deportiva y recreativa que consiste en ascender montañas y realizar actividades en terrenos montañosos. Los alpinistas suelen enfrentarse a condiciones climáticas extremas, terrenos rocosos y elevaciones elevadas durante sus expediciones. El alpinismo puede ser una actividad individual o en grupo, y puede variar en dificultad desde ascensos relativamente fáciles hasta rutas extremadamente técnicas y peligrosas.
El alpinismo requiere habilidades técnicas, físicas y mentales, así como equipo especializado, como cuerdas, arneses, crampones y piolets. Además de ser un desafío físico, el alpinismo también ofrece la oportunidad de disfrutar de paisajes impresionantes y de experimentar la naturaleza de una manera única. Sin embargo, debido a la naturaleza peligrosa de la actividad, es importante que los alpinistas cuenten con la formación adecuada y tomen las precauciones necesarias para garantizar su seguridad.', 'Alpinismo', 8),
('2002-12-02', '13:30:00', 'El desarrollo web es el proceso de crear sitios web y aplicaciones web. Involucra el diseño visual, la usabilidad y la programación para crear experiencias interactivas en línea.', 'Desarrollo Web', 8),
('2002-12-02', '13:40:00', 'Una base de datos es un sistema organizado para almacenar y gestionar grandes volúmenes de información de manera estructurada y accesible. Se utilizan en aplicaciones informáticas para almacenar datos de manera eficiente y permitir su consulta, actualización y gestión. Las bases de datos pueden contener información de todo tipo, como nombres, números, fechas, imágenes, entre otros, y se utilizan en una amplia variedad de aplicaciones, desde sistemas bancarios hasta redes sociales.', 'Base de Datos', 9),
('2002-12-02', '12:30:00', 'La ingeniería industrial es una rama de la ingeniería que se encarga del diseño, mejora e implementación de sistemas integrados de personas, materiales, información, equipos y energía. Su objetivo es optimizar procesos y sistemas complejos para mejorar la eficiencia, la calidad, la productividad y la rentabilidad en diversos tipos de organizaciones y empresas.
Los ingenieros industriales utilizan principios de matemáticas, física, economía y ciencias sociales para analizar y diseñar sistemas de producción, logística, cadena de suministro, control de calidad, entre otros. También se ocupan de temas como la ergonomía, la seguridad laboral y la gestión de proyectos. La ingeniería industrial es una disciplina amplia y versátil que puede aplicarse en una amplia gama de industrias, desde manufactura y producción hasta servicios y consultoría.', 'Ingenieria Industrial', 4),
('2002-12-02', '12:40:00', 'La ingeniería química es una disciplina de la ingeniería que se enfoca en la aplicación de principios de la química, la física, las matemáticas y la economía para el diseño, la producción y la gestión de procesos químicos y biológicos. Los ingenieros químicos trabajan en una amplia variedad de industrias, incluyendo la petroquímica, la farmacéutica, la alimentaria, la energética, la ambiental y la de materiales.
Los ingenieros químicos diseñan y operan plantas de producción química, desarrollan nuevos materiales y productos, investigan y desarrollan procesos para la producción de energía, y trabajan en la gestión ambiental y la seguridad industrial. La ingeniería química juega un papel crucial en la mejora de la eficiencia de los procesos industriales, la reducción de costos, la minimización de impactos ambientales y el desarrollo de nuevos productos y tecnologías.', 'Ingenieria Quimica', 5),
('2002-12-02', '12:50:00', 'La ingeniería de sistemas es una disciplina que se enfoca en el diseño, desarrollo, implementación y gestión de sistemas complejos, tanto físicos como virtuales, para satisfacer las necesidades de las organizaciones o de la sociedad en general. Los ingenieros de sistemas trabajan en una amplia gama de áreas, incluyendo tecnologías de la información, telecomunicaciones, sistemas de transporte, sistemas de energía, entre otros.
La ingeniería de sistemas se basa en principios de ingeniería, gestión, ciencias de la computación, matemáticas y física para abordar problemas complejos y desarrollar soluciones integrales. Los ingenieros de sistemas deben ser capaces de analizar y comprender sistemas complejos en su totalidad, considerando tanto los aspectos técnicos como los sociales, económicos y ambientales.', 'Ingenieria en Sistemas', 6),
('2002-12-02', '12:59:00', 'La ingeniería es la disciplina que se encarga de aplicar conocimientos científicos y técnicos para diseñar, construir, mantener y mejorar estructuras, máquinas, dispositivos, sistemas y procesos en diversos campos. Los ingenieros utilizan principios de matemáticas, ciencia y tecnología para resolver problemas prácticos y mejorar la sociedad en general.
Existen muchas ramas de la ingeniería, como la civil, la mecánica, la eléctrica, la química, la industrial, la informática, entre otras, cada una especializada en diferentes áreas y aplicaciones. La ingeniería juega un papel crucial en el desarrollo de nuevas tecnologías, la infraestructura, la industria, la medicina, la energía, la comunicación y muchos otros aspectos de la vida moderna.', 'Ingenieria', 7),
('2002-12-02', '13:10:00', 'La ingeniería civil es una rama de la ingeniería que se ocupa del diseño, la construcción, la supervisión y el mantenimiento de infraestructuras y obras públicas, como carreteras, puentes, edificios, aeropuertos, sistemas de agua y alcantarillado, entre otros. Los ingenieros civiles aplican principios de matemáticas, física, geología, hidrología y otras ciencias para garantizar que las estructuras sean seguras, duraderas, funcionales y resistentes a las fuerzas naturales y humanas.
La ingeniería civil desempeña un papel fundamental en el desarrollo y la mejora de la calidad de vida de las personas al proporcionar infraestructuras esenciales para la movilidad, el acceso al agua potable, la gestión de residuos, la protección contra desastres naturales y el desarrollo urbano sostenible. Los ingenieros civiles trabajan en estrecha colaboración con arquitectos, urbanistas, geólogos y otros profesionales para llevar a cabo proyectos de construcción de gran envergadura.', 'Ingenieria Civil', 8),
('2002-12-02', '13:20:00', 'La mecatrónica es una disciplina que combina la ingeniería mecánica, la electrónica, la informática y el control automático para diseñar y desarrollar sistemas y productos que incorporen sistemas mecánicos, eléctricos y de software. Los ingenieros mecatrónicos trabajan en el diseño y la implementación de sistemas automatizados y robots, así como en la integración de componentes mecánicos y electrónicos en productos y procesos industriales.
La mecatrónica es una disciplina interdisciplinaria que abarca una amplia gama de aplicaciones, desde la industria automotriz y aeroespacial hasta la robótica médica y la domótica. Los ingenieros mecatrónicos deben tener un conocimiento profundo de diversas áreas de la ingeniería, así como habilidades en programación, diseño de sistemas y control automático. La mecatrónica es una de las áreas de ingeniería de más rápido crecimiento y tiene un papel cada vez más importante en la industria moderna.', 'Mecatronica', 8),
('2002-12-02', '13:30:00', 'La electrónica es una rama de la física y la ingeniería que se ocupa del estudio y la aplicación de los electrones y otros portadores de carga en dispositivos electrónicos. La electrónica abarca desde componentes básicos como resistencias, condensadores y transistores, hasta dispositivos complejos como circuitos integrados y sistemas de comunicación.
Los ingenieros electrónicos diseñan, desarrollan y fabrican dispositivos electrónicos y sistemas, como ordenadores, teléfonos móviles, sistemas de comunicación, equipos médicos, sistemas de control automático, entre otros. La electrónica es una disciplina fundamental en la tecnología moderna y tiene un impacto significativo en casi todos los aspectos de nuestra vida cotidiana.', 'Electronica', 8),
('2002-12-02', '13:40:00', 'La computación es el estudio de los fundamentos teóricos y prácticos de la información y la computación. Involucra el diseño, desarrollo y aplicación de sistemas de computadoras y software para procesar, almacenar y transmitir información de manera eficiente y segura. La computación abarca una amplia gama de áreas, incluyendo la inteligencia artificial, la programación, la ingeniería de software, la seguridad informática, los sistemas distribuidos, entre otros.
Los profesionales en computación, como los científicos de la computación y los ingenieros informáticos, juegan un papel crucial en el desarrollo de tecnologías de la información y la comunicación que son fundamentales para la sociedad moderna. La computación ha revolucionado la forma en que vivimos, trabajamos y nos comunicamos, y continúa siendo una fuerza impulsora detrás de la innovación tecnológica en todo el mundo.', 'Computacion', 9);


-- Insertar 15 categorías
INSERT INTO `Publicaciones`.`Categorias` (nombre, tipo, id_principal, Publicaciones_idPublicaciones) VALUES
('Tecnología', 1, 1, 1),
('Ciencia', 1, 2, 2),
('Arte y Cultura', 1, 3, 3),
('Viajes', 2, 4, 4),
('Deportes', 2, 5, 5),
('Entretenimiento', 2, 6, 6),
('Salud y Bienestar', 1, 7, 7),
('Educación', 2, 8, 8),
('Negocios y Finanzas', 1, 9, 9),
('Medio Ambiente', 1, 10, 10),
('Política', 2, 11, 11),
('Estilo de Vida', 1, 12, 12),
('Historia', 2, 13, 13),
('Alimentación y Nutrición', 2, 14, 14),
('Moda y Belleza', 1, 15, 15);


-- Insertar comentarios
INSERT INTO `Publicaciones`.`Comentarios` (comentario, fecha, Usuarios_idUsuarios, Publicaciones_idPublicaciones) VALUES
('La informacion que se encuentra en este blog es muy buena.', '2024-04-10', 1, 1),
('Muy completa la informacion y precisa.', '2024-04-10', 2, 1),
('Deberian de agregar mas categorias, las que se encuentran estan bien pero hay que ampliarlas.', '2024-04-10', 8, 2),
('Encontre la informacion que necesitaba.', '2024-04-10', 8, 5),
('Satisfecho con la informacion.', '2024-04-10', 5, 8),
('Hay que actualizar la informacion.', '2024-04-10', 6, 6);


-- Select a las publicaciones de 2 subcategorias
SELECT * FROM `Publicaciones`.`Publicaciones`
WHERE `Categorias_idCategorias` IN (SELECT idCategorias FROM `Publicaciones`.`Categorias` WHERE tipo = 2)
LIMIT 1;

-- Select a todas las publicaciones del usuario con id 8, 10, 12
SELECT * FROM `Publicaciones`.`Publicaciones`
WHERE `Publicaciones`.`Usuarios_idUsuarios` IN (8, 10, 12);

-- Select con inner join entre publicaciones y usuarios
SELECT * FROM `Publicaciones`.`Publicaciones`
INNER JOIN `Publicaciones`.`Usuarios` ON `Publicaciones`.`Usuarios_idUsuarios` = `Usuarios`.`idUsuarios`;

-- Select con left join entre publicaciones y usuarios
SELECT * FROM `Publicaciones`.`Publicaciones`
LEFT JOIN `Publicaciones`.`Usuarios` ON `Publicaciones`.`Usuarios_idUsuarios` = `Usuarios`.`idUsuarios`;

-- Select con right join entre publicaciones y usuarios
SELECT * FROM `Publicaciones`.`Publicaciones`
RIGHT JOIN `Publicaciones`.`Usuarios` ON `Publicaciones`.`Usuarios_idUsuarios` = `Usuarios`.`idUsuarios`;

-- Select con inner join entre publicaciones y comentarios
SELECT * FROM `Publicaciones`.`Publicaciones`
INNER JOIN `Publicaciones`.`Comentarios` ON `Publicaciones`.`idPublicaciones` = `Comentarios`.`Publicaciones_idPublicaciones`;

-- Select con left join entre publicaciones y comentarios
SELECT * FROM `Publicaciones`.`Publicaciones`
LEFT JOIN `Publicaciones`.`Comentarios` ON `Publicaciones`.`idPublicaciones` = `Comentarios`.`Publicaciones_idPublicaciones`;

-- Select con right join entre publicaciones y comentarios
SELECT * FROM `Publicaciones`.`Publicaciones`
RIGHT JOIN `Publicaciones`.`Comentarios` ON `Publicaciones`.`idPublicaciones` = `Comentarios`.`Publicaciones_idPublicaciones`;

-- Script de update por lo menos a 5 publicaciones
UPDATE `Publicaciones`.`Publicaciones`
SET titulo_publicacion = 'Nuevo título', descripcion = 'Nuevo contenido'
WHERE idPublicaciones IN (1, 3, 5, 6, 8);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
